### ISSUE TITLE
Back end Integration with Go

### ISSUE THREAD

**Issue by nurulakbaral** [iwdc-oss/raksandi#14]

**Comment by madjiebimaa** [comment]
Ikutan dong bang 😄

**Comment by nurulakbaral** [comment]
> Ikutan dong bang 😄

Gas ji, cuma CRUD doang, kalo bisa pake native go ya wkkwkw pake mux https://www.alexedwards.net/blog/a-recap-of-request-handling, tapi kalo mau framework jg kaya Gin/Echo sabi aja gas, kalo mau langsung ubah aja Assignees ama labelnya (doing)

**Comment by madjiebimaa** [comment]
Siappp bang 🔥
